spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        auth-payment:
          request: auth-payment-request
          response: auth-payment-response
        cancel-payment:
          request: cancel-payment-request
          response: cancel-payment-response
        clearing-payment:
          request: clearing-payment-request
          response: clearing-payment-response
        error-payment:
          request: error-payment-request
          response: error-payment-response

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8090

logging:
  level:
    root: info
