spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  data:
    redis:
     port: 6379
     host: localhost

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

    scheduler:
      account:
        number:
          cron-debit: 0 0 0 * * *
          cron-credit: 0 0 0 * * *
          batch-size: 100

server:
  port: 8090

logging:
  level:
    root: info
